export const PROJECTS_LAYOUT_TYPE = {
  GRID: 'grid',
  TABLE: 'table',
};

export const PROJECTS_GRID_TILE_SIZE = {
  SMALL: 'small',
  LARGE: 'large',
};

export const PROJECTS_TABLE_ROW_HEIGHT = {
  TALL: 'TALL',
  SHORT: 'SHORT',
};

export const DOCUMENT_UPGRADE_OPTIONS = {
  CREATE_NEW_PROJECT: 'CREATE_NEW_PROJECT',
  MOVE_TO_EXISITNG_PROJECT: 'MOVE_TO_EXISITNG_PROJECT',
};
